title: Yongjae Yoo
description: This is my personal site where I document my CVs and random ideas that pop into my head during downtime.
url: https://lowbyyj.github.io
baseurl: ""   
permalink: /:categories/:title/
